name: Image buid

on:
  push:
    branches:
      - 'master'
  schedule:
      - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      image-require-update: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Docker Image Update Checker
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: pihole/pihole:latest
          image: devzwf/pihole-dot-doh:latest
        if: ${{ github.event_name == 'schedule' }}

  build:
    needs: check
    if: ${{ github.event_name != 'schedule' || needs.check.outputs.image-require-update == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Fetch latest release tag
        uses: pozetroninc/github-action-get-latest-release@v0.6.0
        id: latest-tag
        with:
          repository: pi-hole/docker-pi-hole
          
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: |
            devzwf/pihole-dot-doh:latest
            devzwf/pihole-dot-doh:${{ steps.latest-tag.outputs.release }}